name: Mirror scriptrunner-samples

on:
  schedule:
    # Every day at 5:30 am UTC
    - cron: '30 5 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.DEPLOYMENT_KEY_SCRIPTRUNNER_SAMPLES }}
      - name: Mirror repository from Bitbucket
        run: | 
          git clone --mirror https://bitbucket.org/Adaptavist/scriptrunner-samples.git
          cd scriptrunner-samples.git
          git remote set-url --push origin git@github.com:Adaptavist-Bitbucket-Mirror/scriptrunner-samples.git
          echo "Fetching updates from https://bitbucket.org/Adaptavist/scriptrunner-samples.git"
          git fetch -p origin
          echo "Pushing updates to git@github.com:Adaptavist-Bitbucket-Mirror/scriptrunner-samples.git"
          git push --mirror
      - name: Update repostitory description
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo $GH_TOKEN
          gh repo edit Adaptavist-Bitbucket-Mirror/scriptrunner-samples --description "Updated on 2024-03-11 from https://bitbucket.org/Adaptavist/scriptrunner-samples.git"
      
